In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [9]:
data = pd.read_csv('drug.csv')
data

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [10]:
label = LabelEncoder()
for col in data.columns:
    data[col] = label.fit_transform(data[col])
data

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0      8    0   0            0      167     0
1     30    1   1            0       89     3
2     30    1   1            0       43     3
3     12    0   2            0       10     4
4     44    0   1            0      133     0
..   ...  ...  ..          ...      ...   ...
195   39    0   1            0       69     3
196    1    1   1            0       75     3
197   35    1   2            0       36     4
198    8    1   2            1      102     4
199   24    0   1            1       66     4

[200 rows x 6 columns]

In [11]:
X_data = data.iloc[:,:-1].values
Y_data = data.iloc[:,-1].values
x_train,x_test,y_train,y_test = train_test_split(X_data,Y_data,test_size=0.3,random_state=42)

In [12]:

gauss_nb_model = GaussianNB()
gauss_nb_model.fit(x_train,y_train)

GaussianNB()

In [13]:
y_predictions = gauss_nb_model.predict(x_test)

In [14]:
accr = accuracy_score(y_test,y_predictions)
print(f"ACCURACY : {accr*100}%")

cm=confusion_matrix(y_test,y_predictions)
print("CONFUSION MATRIX :\n",cm)

tp=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]

precision = tp/(tp+fp)
recall = tp/(tp+fn)
print(f"PRECISION : {precision*100}%")
print(f"RECALL : {recall*100}%")

ACCURACY : 88.33333333333333%
CONFUSION MATRIX :
 [[19  2  3  2  0]
 [ 0  7  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  6  0]
 [ 0  0  0  0 18]]
PRECISION : 90.47619047619048%
RECALL : 100.0%
